### ISSUE TITLE
Disable pinch/zoom for mobile devices?

### ISSUE THREAD

**Issue by squiggleuk** [lasselukkari/DuinoDCX#117]
**Describe the bug**
When viewing interface on iOS, double tapping and pinching causes the app to zoom - The app is mobile optimised, so this is unnecessary 

**To Reproduce**
1. Use iOS/safari.
2. Go to main screen
3. double click on + or minus button
4. observe  that the app has zoomed

**Expected behavior**
shouldn't zoom. I suspect adjustment to HTML viewport is needed?
<meta name=”viewport” content=”width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no” />

**Smartphone (please complete the following information):**
 - Device: iPhone10
 - OS: ios 12
 - Browser safari

**Hardware (please complete the following information):**
 - Demo

 
**Additional context**
Unrelated, but I set out to complete a similar project ages ago... (https://github.com/squiggleuk/UltradrivePi) - Really happy to find you managed to create this!!! :)

**Comment by lasselukkari** [comment]
I'll try to have time to fix this during the weekend.
