### ISSUE TITLE
Sketch too big

### ISSUE THREAD

**Issue by samovesel** [lasselukkari/DuinoDCX#23]
Hi, when I try to compile and upload to ESP32 board (doit esp32 devkit v1), sketch becomes too big. 

Output:
Sketch uses 1316078 bytes (100%) of program storage space. Maximum is 1310720 bytes.

Global variables use 99344 bytes (30%) of dynamic memory, leaving 228336 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board DOIT ESP32 DEVKIT V1.

Arduino version 1.8.7

What am I doing wrong?

**Comment by lasselukkari** [comment]
Thanks for contributing. I have updated the readme about the correct Partition Scheme.
