### ISSUE TITLE
searching 

### ISSUE THREAD

**Issue by davidd1205** [lasselukkari/DuinoDCX#237]
159/5000
Hello
![IMG_0190](https://user-images.githubusercontent.com/6397779/84751853-56e8d280-afbd-11ea-80ba-c705793762be.jpg)
![IMG_0191](https://user-images.githubusercontent.com/6397779/84751885-60723a80-afbd-11ea-9f18-9af748cf304a.jpg)
![IMG_0191](https://user-images.githubusercontent.com/6397779/84751879-5e0fe080-afbd-11ea-9155-0f70886e8fdd.jpg)
![IMG_0192](https://user-images.githubusercontent.com/6397779/84751896-649e5800-afbd-11ea-8150-54e207c6741a.jpg)
![IMG_0192](https://user-images.githubusercontent.com/6397779/84751898-6536ee80-afbd-11ea-9343-8bb24c425f31.jpg)

I'm stuck on the searching page
Last update
dcx firmware latest 1.18 model 2016
esp32s
tested with hardware but ok even without bridge

**Comment by lasselukkari** [comment]
The Ultradrive model you have should work just fine. Did you verify your setup with a multimeter? If not, do that first before we go any deeper in with the debugging.

**Comment by davidd1205** [comment]
thanks a lot 

i have tested on esp32s and the voltage rx tx is ok

but on a max232 i don't have a voltage 
i think my max232 is fault 

i dont have another for test
