### ISSUE TITLE
No DuinoDcx page access after flashing

### ISSUE THREAD

**Issue by Sonik-audiolab** [lasselukkari/DuinoDCX#245]
Hi.
Tried to build a Duino DCX kit.
I'm under Linux Mint 20.
I had troubles to get Arduino Ide working.
I solved searching on the web.
Everything ok till flashing Sketchup on ESP32.
Process gone well
I get the message of UPLOAD completed till the last step.

"Leaving. Hard resetting via RTS pin..."

ESP32 starts to transmit WIFI.
I can log in.
When I go to the ip address 192.168.4.1 the page stuck on "SEARCHNG"
I have access to pages WIFI SETUP, SETTINGs and FIRMWARE UPDATE.
And that's it.

Tried to install,with clean install , NODEjs and ARDUINo IDE but nothing is changed.
I can flash again the board but with the same results.

Trying to enter with Mac, Iphone and Ipad. Same issue.

![2020-11-22_11-07](https://user-images.githubusercontent.com/74857959/99902096-249d7880-2cb3-11eb-9426-99686ec25130.png)

Maybe I prepared a bad folder to upload.
In the release folder I have these files.

![2020-11-22_11-11](https://user-images.githubusercontent.com/74857959/99902152-81992e80-2cb3-11eb-90cf-c5fa97f9384b.png)

Any Idea of where I'm getting wrong?
thanks

**Comment by Sonik-audiolab** [comment]
I forgot...
I follwed step by step .
Everything well except this .

![2020-11-22_11-17](https://user-images.githubusercontent.com/74857959/99902279-84485380-2cb4-11eb-8ee4-9c534bfd5cb6.png)

**Comment by Sonik-audiolab** [comment]
...sorry again.
I'm new on this and trying to learn step by step.
Understood that I misse one step.
I change directory to Duinodcx folder where package.json is located.
My Duino folder is like this.
![2020-11-22_12-19](https://user-images.githubusercontent.com/74857959/99903554-0e94b580-2cbd-11eb-89eb-09827170ebba.png)


Now I'm in Duinodcx folder and I launch the two commands
![2020-11-22_12-21](https://user-images.githubusercontent.com/74857959/99903603-4ac81600-2cbd-11eb-8dca-25bfc21c3928.png)
![2020-11-22_12-21_1](https://user-images.githubusercontent.com/74857959/99903607-4dc30680-2cbd-11eb-94ef-fc35d93f0d82.png)

Now the Duinodcx folder is like this
![2020-11-22_12-16](https://user-images.githubusercontent.com/74857959/99903625-5ca9b900-2cbd-11eb-9eb6-73746400c330.png)

Then I open Duinodcx.ino with Arduino IDE.
I upload sketch.
After this try to connect again to DCX2496 wifi.
When  enter to Ip I get the same stuck page.
![2020-11-22_11-07](https://user-images.githubusercontent.com/74857959/99903671-a5617200-2cbd-11eb-804a-eaa0a7c496ad.png)

**Comment by lasselukkari** [comment]
Please read the [instructions](https://lasselukkari.github.io/DuinoDCX/) again carefully and follow them step by step. Also take a look at the closed issues from the past.  Your comments reveal that you have not done neither of th yet. All the information is there and I would be just repeating myself.

**Comment by Sonik-audiolab** [comment]
ok. Thank you for you time spent to answer me.
So I got wrong.
Nodejs process is needed just to modify the code.
Sorry. I've seen to late other issues post closed.
Now I've seen. So I will repeat the sketch upload without making troubles with Nodejs.
In case I will get again problem now I know how to use the testing fil.
For sure I forgot to say you..
Nice job with this kit and software.
Thank you.

**Comment by Sonik-audiolab** [comment]
Sorry man. 
So please sorry... I need to ask you 2 things more to confirm that I understood well.
I'm stupid maybe.
1) I didn't understand about test.
Hardware test needs to be done with null cable connected right?
2)It stucks on "Searching" because does not receive signal form DCX2496. Right?

I ordered to build 2 kits. Assembled the other and I get the same result.
Doing hardware test also the same. I get "error".
Tried to upload Duino sketch to booth of them.
I can connect to wifi but the couple stuck in searching.
So, if I understood well, I get error from test and also user page stucks in searching because I bought wrong cables.
They are simple Rs232 serial lineDB9.

**Comment by lasselukkari** [comment]
The hardware tests need to be done with the complete setup including the cabling your are planning to plug to the dcx2496. There are two types of cables available: null modem and straight. Do a quick google search and you will see the difference. You need a null modem cable. But because male to male null modem cables are really rare you need to use a male to male gender changer and then female to male null modem cable. You can use a multimeter to detect what type of cable you have bought.

Do you have the gender changer in your setup? If not you are most likely using the wrong type of cable.

**Comment by Sonik-audiolab** [comment]
Ok. Thanks a lot. I took a mistake when bought all the parts. I really missed NULL and ordered a serial Rs232 “ male to female”. Today I bought Null cable and it works great in booth kits.
Now ordered null “male to male” adapter to don’t waste the wrong cables.
Again thanks. 
![7EBAC0EA-6FEC-44B0-A803-42AABF08DDE1](https://user-images.githubusercontent.com/74857959/100012291-f01ce000-2dca-11eb-811a-c770b5faee60.png)

**Comment by lasselukkari** [comment]
I'm glad you got it working.

**Comment by Sonik-audiolab** [comment]
Thank you man. Dcx users all around the world have to say you a really big “THANKS!”
It’s really an useful tool to have. Great job.
