### ISSUE TITLE
Add MUTE function for SUM 

### ISSUE THREAD

**Issue by soundavinci** [lasselukkari/DuinoDCX#249]
On the level overview and Mute tab the SUM chain is missing. Muting e.g. A+B inputs is not muting the SUM chain.

It would be nice to have also the SUM chain accessible like the inputs ABC.  

Create project!

**Comment by lasselukkari** [comment]
I have not even noticed before that the device actually has a function to mute the sum channel. If it works like the rest of the channels there it should be easy to implement.

**Comment by lasselukkari** [comment]
This turned out to be easier than expected. It's just missing from the ui.

**Comment by lasselukkari** [comment]
<img width="472" alt="Screenshot 2020-12-12 at 16 15 22" src="https://user-images.githubusercontent.com/1687972/101986419-6019da00-3c96-11eb-896e-145595ee0638.png">

The feature is now available with the latest release: https://github.com/lasselukkari/DuinoDCX/releases/tag/v0.0.39

**Comment by soundavinci** [comment]
Hello Lasse,
That was fast. Thanks a lot. I will test the version in the next days!
Thanks again for the great effort providing this SW solution for the DCX!

BR soundavinci
