### ISSUE TITLE
Static files not found

### ISSUE THREAD

**Issue by samovesel** [lasselukkari/DuinoDCX#25]
Hi,
sorry to bother you, but I can't get to compile sketch right. I followed your instructions, and everything seems OK, but when I upload it to ESP32 looks like there are no files in /static folder, so the only thing I can do is login and then it stops, since I can't load  /static/css/main.c8aa8249.css and /static/js/main.aa0c02d7.js.
manifest.json & favicon.ico are present.
The operating system is Win 7. 

And I get some warnings during compilation in Arduino:
j:\TEMP\arduino_build_201636\sketch\StaticFiles.h: In function 'void ServeStatic(WebApp*)':
j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50166:12: warning: unknown escape sequence: '\c'
   app->get("static\css\main.c8aa8249.css", &static_static_css_main_c8aa8249_css);

            ^

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50166:12: warning: unknown escape sequence: '\m'

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50167:12: warning: unknown escape sequence: '\m'

   app->get("static\media\glyphicons-halflings-regular.448c34a5.woff2", &static_static_media_glyphicons_halflings_regular_448c34a5_woff2);

            ^

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50167:12: warning: unknown escape sequence: '\g'

In file included from J:\My Documents\Arduino\DuinoDCX-master\DuinoDCX\DuinoDCX.ino:8:0:

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50168:12: warning: unknown escape sequence: '\m'

   app->get("static\media\glyphicons-halflings-regular.89889688.svg", &static_static_media_glyphicons_halflings_regular_89889688_svg);

            ^

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50168:12: warning: unknown escape sequence: '\g'

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50169:12: warning: unknown escape sequence: '\m'

   app->get("static\media\glyphicons-halflings-regular.e18bbf61.ttf", &static_static_media_glyphicons_halflings_regular_e18bbf61_ttf);

            ^

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50169:12: warning: unknown escape sequence: '\g'

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50170:12: warning: unknown escape sequence: '\m'

   app->get("static\media\glyphicons-halflings-regular.f4769f9b.eot", &static_static_media_glyphicons_halflings_regular_f4769f9b_eot);

            ^

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50170:12: warning: unknown escape sequence: '\g'

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50171:12: warning: unknown escape sequence: '\m'

   app->get("static\media\glyphicons-halflings-regular.fa277232.woff", &static_static_media_glyphicons_halflings_regular_fa277232_woff);

            ^

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50171:12: warning: unknown escape sequence: '\g'

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50172:12: warning: unknown escape sequence: '\j'

   app->get("static\js\main.aa0c02d7.js", &static_static_js_main_aa0c02d7_js);

            ^

j:\TEMP\arduino_build_201636\sketch\StaticFiles.h:50172:12: warning: unknown escape sequence: '\m'

Samo

**Comment by samovesel** [comment]
OK, I just needed to replace backslashes with slashes in void ServeStatic in StaticFiles.h and then everything is OK. Is there something I 'm doing wrong during building?

**Comment by lasselukkari** [comment]
I actually most likely know the problem already. It's because paths in windows use '\' rather than '/'. I will update the tooling to fix this. Should get it done tonight.

**Comment by lasselukkari** [comment]
I updated the library that generates the static payloads. Can try again with the latest version in the master branch?

**Comment by samovesel** [comment]
First backslash is now ok, but the problem is still there:

void ServeStatic(WebApp* app) {
  app->get("asset-manifest.json", &static_asset_manifest_json);
  app->get("favicon.ico", &static_favicon_ico);
  app->get("", &static_index);
  app->get("manifest.json", &static_manifest_json);
  app->get("static/css\main.c8aa8249.css", &static_static_css_main_c8aa8249_css);
  app->get("static/js\main.99370a8c.js", &static_static_js_main_99370a8c_js);
  app->get("static/media\glyphicons-halflings-regular.448c34a5.woff2", &static_static_media_glyphicons_halflings_regular_448c34a5_woff2);
  app->get("static/media\glyphicons-halflings-regular.89889688.svg", &static_static_media_glyphicons_halflings_regular_89889688_svg);
  app->get("static/media\glyphicons-halflings-regular.e18bbf61.ttf", &static_static_media_glyphicons_halflings_regular_e18bbf61_ttf);
  app->get("static/media\glyphicons-halflings-regular.f4769f9b.eot", &static_static_media_glyphicons_halflings_regular_f4769f9b_eot);
  app->get("static/media\glyphicons-halflings-regular.fa277232.woff", &static_static_media_glyphicons_halflings_regular_fa277232_woff);

**Comment by lasselukkari** [comment]
True. I should have known this... I have now changed it to `relativePath.replace(/\\/g, '/')`. I really should write unit tests for the tooling or alternatively stop coding drunk on friday nights and go out. Can you try again.

**Comment by samovesel** [comment]
Everything is perfect now. And that mute / unmute toggle button is really useful. Thank you!
