### ISSUE TITLE
Searching...

### ISSUE THREAD

**Issue by dmoutault** [lasselukkari/DuinoDCX#255]
Hello,

First of all, thank you for this work!

I have a problem, when connecting to the web page, I get stuck on "Searching…"
What did I do wrong?

**Comment by lasselukkari** [comment]
Hello! Please read the closed issues first. This has been answered many time.

**Comment by lasselukkari** [comment]
I hope you got the problem solved. If not I can help you to find the issue. At this point I have helped so many people with this same thing that the troubleshooting should be straightforward. If there is something that could be improved in the instructions please let me know.
