### ISSUE TITLE
After install and Opening "http://192.168.4.1" it just says "searching" 

### ISSUE THREAD

**Issue by Fijo112** [lasselukkari/DuinoDCX#262]
Hello peoples,
I install DuinoDCX, but after connecting to the Wifi it creates and opening http://192.168.4.1 it will load the site but it stops at searching, can wait an hour without it advancing, I tried factory resetting the esp32 and different Verions of DuinoDCX, nothing changes, but I can make an OTA, only the UI dosn't load.

Thanks for any help!

**Comment by lasselukkari** [comment]
https://github.com/lasselukkari/DuinoDCX/issues/260
https://github.com/lasselukkari/DuinoDCX/issues/255
https://github.com/lasselukkari/DuinoDCX/issues/244
https://github.com/lasselukkari/DuinoDCX/issues/237
https://github.com/lasselukkari/DuinoDCX/issues/85
