### ISSUE TITLE
Bessel filter plot

### ISSUE THREAD

**Issue by samovesel** [lasselukkari/DuinoDCX#65]
Hi,
it seems that there is something wrong with crossover plot formula for bessel filter. Center frequency is just off for bes12 & bes24. Or am I missing something?

Best!

![bes24](https://user-images.githubusercontent.com/17411122/58441374-dfaa7d00-80e1-11e9-932a-9dda484b66fd.jpg)
![bes12](https://user-images.githubusercontent.com/17411122/58441375-dfaa7d00-80e1-11e9-8cd3-dd48a49addd9.jpg)

**Comment by lasselukkari** [comment]
Thanks for reporting. I will investigate this.

**Comment by lasselukkari** [comment]
I consulted Ilkka Huhtakallio, the mastermind behind the the transfer function code. He was quickly able to pinpoint the problem.

**Comment by samovesel** [comment]
Perfect, thank you! 
I know it might be overengeenering, but I have one more suggestion for the plot.
It would be really nice to have combined freq response curve (maybe also with included eq curves) on crossover plot. 
Not to mention phase response.
That would be really useful, maybe even as standalone project, since it's really annoying to find that kind of stuff online.
But, like I said, it's probably not in the scope of duinoDCX.

Best!
