### ISSUE TITLE
User interface is stuck to "Searching..." 

### ISSUE THREAD

**Issue by Jost9696** [lasselukkari/DuinoDCX#85]
Hello, 
I want to install everything into the DCX with a switch. I have already a small 5V Powersupply and this chip https://www.ebay.de/itm/MAX3232-ESE-RS232-auf-TTL-Converter-Module-Konverter-Board-6-St%C3%BCck-piece/173358084088?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

I conntecte the TX and RX from the ESP32 to the small chip and the 3.3 V. the cabel to the Controller only is connected with GND RX and TX. In my fault I try to short RTS and CTS and now I killed my EEprom i think. I ordered a new one already. The software works so i can see searching on my phone. But there is no connection.

**Comment by lasselukkari** [comment]
Shorting the RTS and CTS should not cause problems. Infact linking input and output of the RS232 chip can be used to verify the electrical connections. When the output goes high the input should read high as well.

I will post you an Arduino sketch later today that you can use to verify that your electrical connection are working as intended. You will need a multimeter to complete the test.

**Comment by lasselukkari** [comment]
Also verify that you have the correct setting selected in the Ultradrive for the `SETUP -> MISCELLANEOUS -> PORT` setting.

![port-setting](https://user-images.githubusercontent.com/1687972/62522367-39de6180-b83a-11e9-8caa-b439b93a0da9.jpg)

**Comment by lasselukkari** [comment]
I have added a [HarwareTest sketch](https://github.com/lasselukkari/DuinoDCX/blob/master/HardwareTest/HardwareTest.ino) to the project.

**Comment by Jost9696** [comment]
Now the test works everything shown as okay in the serial monitor. Thank you. (Y)

**Comment by Corylus-Core** [comment]
My Setup is also stuck in "Searching". Already tried to change RX and TX but nothing happened. I saw that there is a HardwareTest.ino which i've tried with looping the RX and TX pins on the cable to the DCX2496, but i don´t understand how i get the readout from you HardwareTest.ino. Sorry for my stupid questions :-( . Sincerely Georg

**Comment by lasselukkari** [comment]
Hi.

Could you take a picture of your setup and a give a full list of components in your wiring chain? I may be able to help.

To use the HardwareTest.ino open it in the Arduino IDE to flash it to the board. Then open `Tools -> Serial Monitor` and set the baud rate to `115200`. You will now see the text `Error` or `OK` in output repeated every 2 seconds.
